// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exchangeRateList.Dat;

#nullable disable

namespace exchangeRateList.Migrations
{
    [DbContext(typeof(ExchanceDbContext))]
    partial class ExchanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("exchangeRateList.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CnbMid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrBuy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrMid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrSell")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EcbMid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Move")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValBuy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValMid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValSell")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });
#pragma warning restore 612, 618
        }
    }
}
